default_context:
  author_email: firstname@datajoint.com
  author_name: FirstName LastName
  docs_url: https://dj-sciops.github.io/o-science-institute_w-neuro-lab
  github_repo: o-science-institute_w-neuro-lab
  github_user: dj-sciops
  homepage_url: https://github.com/dj-sciops
  lab: Neuro Lab
  organization: Science Institute
  pkg_version: 0.0.1
  python_version: '3.9'
